apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wasp.fullname" . }}-dashboard-credentials
  labels: {{- include "wasp.labels" . | nindent 4 }}
data:
  username: {{ .Values.wasp.dashboard.auth.username | b64enc }}
  password: {{ .Values.wasp.dashboard.auth.password | b64enc }}