{{- $fullName := include "goshimmer.fullname" . -}}
{{- if .Values.goshimmer.seed -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.goshimmer.seedSecretName | default $fullName }}-seed
  labels: {{- include "goshimmer.labels" . | nindent 4 }}
data:
  seed: {{ .Values.goshimmer.seed | b64enc }}
{{- end }}
---
{{ if .Values.goshimmer.dashboard.auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-dashboard-credentials
  labels: {{- include "goshimmer.labels" . | nindent 4 }}
data:
  username: {{ .Values.goshimmer.dashboard.auth.username | b64enc }}
  password: {{ .Values.goshimmer.dashboard.auth.password | b64enc }}
{{- end }}